version: '3'

services:
  react-app:
    environment:
      - CHOKIDAR_USEPOLLING=true
    build: 
      context: .
      args:
        - REACT_APP_SERVICES_HOST=/services/m
    ports:
      - '8080:80'
    networks: 
      - fronted

networks: 
  fronted:

# version: '3'

# services:
#   react-app:
#     environment:
#       - CHOKIDAR_USEPOLLING=true
#     build: 
#       context: .
#       dockerfile: Dockerfile.dev
#     ports:
#       - '3000:3000'
#     volumes:
#       - /app/node_modules
#       - .:/app
#   tests:
#     build: 
#       context: .
#       dockerfile: Dockerfile.dev
#     volumes:
#       - /app/node_modules
#       - .:/app
#     command: ["npm", "run", "test"]    